# Generated by Django 2.2.4 on 2019-08-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_clip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='clip',
        ),
        migrations.AddField(
            model_name='course',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
