# Generated by Django 2.2.4 on 2019-08-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190819_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='website',
        ),
        migrations.AddField(
            model_name='course',
            name='clip',
            field=models.FileField(blank=True, null=True, upload_to='user_video/'),
        ),
    ]
