# Generated by Django 2.2.4 on 2019-08-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190819_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='clip',
            field=models.ImageField(upload_to='user_video/'),
        ),
    ]
