# Generated by Django 2.2.4 on 2019-08-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190819_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='clip',
        ),
    ]
