# Generated by Django 2.2.4 on 2019-08-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190819_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='website',
        ),
    ]
