# Generated by Django 2.2.4 on 2019-08-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_course_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='site',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
